<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="EventTrackerApi.Tests\**\*.cs" />
    <Content Remove="EventTrackerApi.Tests\**\*" />
    <None Remove="EventTrackerApi.Tests\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="EventApi_Sprint5\**\*.cs" />
    <Content Remove="EventApi_Sprint5\**\*" />
    <None Remove="EventApi_Sprint5\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
  </ItemGroup>

</Project>
